# Generated by Django 5.1 on 2024-10-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('prs_nbr', models.AutoField(primary_key=True, serialize=False)),
                ('prs_name', models.CharField(max_length=100)),
                ('prs_skill', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDataset',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.person')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('accs_id', models.AutoField(primary_key=True, serialize=False)),
                ('accs_date', models.DateField(auto_now_add=True)),
                ('accs_added', models.DateTimeField(auto_now_add=True)),
                ('accs_prsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.person')),
            ],
        ),
    ]
