# Generated by Django 5.1 on 2024-10-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assignment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fess',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('mode', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
    ]
