# Generated by Django 5.1 on 2024-10-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fess',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
