# Generated by Django 5.1 on 2024-10-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_fess_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fess',
            name='transaction_id',
            field=models.CharField(max_length=12),
        ),
    ]
