# Generated by Django 5.1 on 2024-10-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('exam_type', models.CharField(max_length=50)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subjects')),
            ],
        ),
    ]
